In [3]:
import pandas as pd
import numpy as np
#data=pd.read_csv(".\\Iris.csv")
data=pd.read_csv("C:\\Users\\exam2\\Desktop\\Iris.csv")
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
arr=np.array(data)
arr

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
 

In [5]:
a=np.delete(arr,4,axis=1)
a

array([[1, 5.1, 3.5, 1.4, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 'Iris-setosa'],
       [22, 5.1, 3.7, 1.5, 'Iris-setosa'],
       [23, 4.6, 3.6, 1.0, 'Iris-setosa'],
       [24, 5.1, 3.3

In [6]:
s=np.shape(arr)
print(s)
d=np.ndim(arr)
print(d)
si=np.size(arr)
print(si)

(150, 6)
2
900


In [13]:
header = np.array(["sepallength", "sepalwidth", "petallength", "petalwidth", "speciesNo"])

In [14]:
print(header)

['sepallength' 'sepalwidth' 'petallength' 'petalwidth' 'speciesNo']


In [34]:
iris_avg=np.array(data.mean()).round(2)
iris_min=np.array(data.min())
iris_max=np.array(data.max())
iris_std=np.array(data.std()).round(2)
iris_var=np.array(data.std()**2).round(2)
print(iris_min)
print(iris_max)
print(iris_avg)
print(iris_std)
print(iris_var)

[1 4.3 2.0 1.0 0.1 'Iris-setosa']
[150 7.9 4.4 6.9 2.5 'Iris-virginica']
[75.5   5.84  3.05  3.76  1.2 ]
[43.45  0.83  0.43  1.76  0.76]
[1.8875e+03 6.9000e-01 1.9000e-01 3.1100e+00 5.8000e-01]


C:\Users\exam2\AppData\Local\Temp\ipykernel_10776\3030723363.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris_avg=np.array(data.mean()).round(2)
C:\Users\exam2\AppData\Local\Temp\ipykernel_10776\3030723363.py:4: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris_std=np.array(data.std()).round(2)
C:\Users\exam2\AppData\Local\Temp\ipykernel_10776\3030723363.py:5: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only